#ifndef FENETRE_PRINCIPALE_CONSTANTS_H
#define FENETRE_PRINCIPALE_CONSTANTS_H

typedef enum GSB_GENERAL_NOTEBOOK_PAGES {
    GSB_HOME_PAGE,
    GSB_ACCOUNT_PAGE,
    GSB_SCHEDULER_PAGE,
    GSB_PAYEES_PAGE,
    GSB_CATEGORIES_PAGE,
    GSB_BUDGETARY_LINES_PAGE,
    GSB_REPORTS_PAGE,
#ifdef HAVE_G2BANKING
    GSB_AQBANKING_PAGE,
#endif
} GsbGeneralNotebookPages;

#endif
