# define TRANSACTION_FORM_DATE 1
# define TRANSACTION_FORM_DEBIT 2
# define TRANSACTION_FORM_CREDIT 3
# define TRANSACTION_FORM_VALUE_DATE 4
# define TRANSACTION_FORM_EXERCICE 5
# define TRANSACTION_FORM_PARTY 6
# define TRANSACTION_FORM_CATEGORY 7
# define TRANSACTION_FORM_FREE 8  /* free for the moment, to be fill with a new thing */
# define TRANSACTION_FORM_BUDGET 9
# define TRANSACTION_FORM_NOTES 10
# define TRANSACTION_FORM_TYPE 11
# define TRANSACTION_FORM_CHEQUE 12
# define TRANSACTION_FORM_DEVISE 13
# define TRANSACTION_FORM_CHANGE 14
# define TRANSACTION_FORM_VOUCHER 15
# define TRANSACTION_FORM_BANK 16
# define TRANSACTION_FORM_CONTRA 17
# define TRANSACTION_FORM_OP_NB 18
# define TRANSACTION_FORM_MODE 19
# define TRANSACTION_FORM_WIDGET_NB 19

/* Constantes pour style_entree_formulaire[] */
# define ENCLAIR 0
# define ENGRIS 1


