#ifndef _PARAMETRES_H
#define _PARAMETRES_H (1)

/* Preference pages */
enum preference_page  {
    NOT_A_PAGE = -1,
    FILES_PAGE,
    IMPORT_PAGE,
    SOFTWARE_PAGE,
    FONTS_AND_LOGO_PAGE,
    MESSAGES_AND_WARNINGS_PAGE,
    ADDRESSES_AND_TITLES_PAGE,
    TOTALS_PAGE,
    TOOLBARS_PAGE,
    TRANSACTIONS_PAGE,
    RECONCILIATION_PAGE,
    RECONCILIATION_SORT_PAGE,
    TRANSACTION_FORM_PAGE,
    TRANSACTION_FORM_BEHAVIOR_PAGE,
    TRANSACTION_FORM_COMPLETION_PAGE,
    CURRENCIES_PAGE,
    CURRENCY_LINKS_PAGE,
    BANKS_PAGE,
    FINANCIAL_YEARS_PAGE,
    METHODS_OF_PAYMENT_PAGE,
    NUM_PREFERENCES_PAGES
};
/* START_INCLUDE_H */
#include "parametres.h"
/* END_INCLUDE_H */


/*START_DECLARATION*/
void preferences ( gint page );
/*END_DECLARATION*/

#endif

